name: Check formatting

on:
  push:
  pull_request:

check:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: |
          npm i -g yarn
          yarn
      - name: Check formatting
        run: yarn fmt:check